; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html
;
; M5StickC Plus FactoryTest demo
; Source: https://github.com/m5stack/M5StickC-Plus/tree/master/examples/FactoryTest

[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino

lib_deps =
    m5stack/M5StickCPlus

monitor_speed = 115200
upload_port = /dev/cu.usbserial-3552BBE64F
monitor_port = /dev/cu.usbserial-3552BBE64F
