
# docker build -t acct/python-2.7 .
# docker run -i -p 8008:8000 -t python/server
# curl http://localhost:8008/

FROM  centos:6
RUN   yum install -y centos-release-SCL  &&  yum install -y python27
RUN   ln -s /opt/rh/python27/root/usr/bin/python2.7 /usr/local/bin/python  &&  ln -s /opt/rh/python27/root/usr/bin/python2.7 /usr/local/bin/python2.7
RUN   ln -s /opt/rh/python27/root/usr/bin/easy_install-2.7 /usr/local/bin/easy_install
RUN   echo /opt/rh/python27/root/usr/lib64  >>     /etc/ld.so.conf  &&  ldconfig
RUN   easy_install pip
RUN   ln -s /opt/rh/python27/root/usr/bin/pip2.7  /usr/local/bin/pip
RUN   pip install requests
RUN   yum install -y mlocate  &&  updatedb  &&  locate easy_install  &&  locate libpython2.7.so.1.0  &&  locate pip

# EXPOSE  80

WORKDIR /var/tmp/  # like `cd`
COPY    Dockerfile-scl  Dockerfile.txt

CMD ["python", "-m", "SimpleHTTPServer", "8000"] 

