#!/bin/bash

# QT2040 Trinkey Deployment Script with Provenance Tracking
# Generates metadata file named {basename}-{filesize}.md for tracking deployed code

DEVICE_PATH="/Volumes/CIRCUITPY"
SOURCE_FILE="${1:-code.py}"

echo "QT2040 Trinkey Deployment Script"
echo "================================"

# Check if the device is connected
if [ ! -d "$DEVICE_PATH" ]; then
    echo "❌ Error: QT2040 Trinkey not found at $DEVICE_PATH"
    echo "   Make sure your device is connected and mounted"
    exit 1
fi

# Check if source file exists
if [ ! -f "$SOURCE_FILE" ]; then
    echo "❌ Error: $SOURCE_FILE not found in current directory"
    exit 1
fi

echo "📱 Found QT2040 Trinkey at $DEVICE_PATH"
echo "📄 Deploying $SOURCE_FILE..."

# Get file metadata
BASENAME=$(basename "$SOURCE_FILE" .py)
SOURCE_DIR=$(dirname "$SOURCE_FILE")
FILESIZE=$(wc -c < "$SOURCE_FILE" | tr -d ' ')
CHECKSUM=$(shasum -a 256 "$SOURCE_FILE" | awk '{print $1}')
DATE_UPDATED=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S %Z" "$SOURCE_FILE")
DATE_DEPLOYED=$(date "+%Y-%m-%d %H:%M:%S %Z")

# Source metadata file (lives next to the .py file)
SOURCE_METADATA="${SOURCE_DIR}/${BASENAME}.md"

# Destination metadata file (size-prefixed for device)
DEST_METADATA="${FILESIZE}-${BASENAME}.md"

echo "📝 Updating metadata: $SOURCE_METADATA"

# Check if source metadata exists, if not create template
if [ ! -f "$SOURCE_METADATA" ]; then
    echo "   Creating new metadata file..."
    cat > "$SOURCE_METADATA" << 'EOF'
# Script Metadata

## Description

Add notes about what this script does here...

## Hardware Requirements

- Board: (e.g., QT2040 Trinkey, RP2350 Pimoroni Tiny2350)
- Peripherals: (e.g., None, I2C OLED, NeoPixels)

## Notes

<!-- Deployment details auto-updated below by deploy-circuitpy.sh -->

EOF
fi

# Update/append deployment section in source metadata
# First, remove any existing deployment section
sed -i.bak '/^---$/,/^$/d' "$SOURCE_METADATA" 2>/dev/null || true
rm -f "${SOURCE_METADATA}.bak"

# Append current deployment info
cat >> "$SOURCE_METADATA" << EOF

---

## Latest Deployment

**Deployed to:** CircuitPython Device (CIRCUITPY)  
**Original Filename:** \`$SOURCE_FILE\`  
**File Size:** $FILESIZE bytes  
**Date File Updated:** $DATE_UPDATED  
**Date Deployed:** $DATE_DEPLOYED  
**SHA256 Checksum:** \`$CHECKSUM\`

### Verification

\`\`\`bash
# Check filesize
ls -l /Volumes/CIRCUITPY/code.py | awk '{print \$5}'
# Expected: $FILESIZE

# Check checksum
shasum -a 256 /Volumes/CIRCUITPY/code.py
# Expected: $CHECKSUM
\`\`\`
EOF

# Copy source metadata to destination with size prefix
cp "$SOURCE_METADATA" "$DEST_METADATA"

# Copy the source file as code.py
cp "$SOURCE_FILE" "$DEVICE_PATH/code.py"

if [ $? -ne 0 ]; then
    echo "❌ Error: Failed to deploy $SOURCE_FILE"
    exit 1
fi

# Copy the metadata file to device
cp "$DEST_METADATA" "$DEVICE_PATH/$DEST_METADATA"

if [ $? -ne 0 ]; then
    echo "⚠️  Warning: Failed to copy metadata file (but code.py deployed successfully)"
fi

# Update settings.toml with current deployment info
SETTINGS_FILE="$DEVICE_PATH/settings.toml"
TEMP_SETTINGS=$(mktemp)

echo "📝 Updating settings.toml with deployment metadata..."

# Preserve existing settings, remove old deployment metadata
if [ -f "$SETTINGS_FILE" ] && [ -s "$SETTINGS_FILE" ]; then
    grep -v "^DEPLOYED_" "$SETTINGS_FILE" > "$TEMP_SETTINGS" 2>/dev/null || true
    # Add blank line if file has content
    if [ -s "$TEMP_SETTINGS" ]; then
        echo "" >> "$TEMP_SETTINGS"
    fi
else
    touch "$TEMP_SETTINGS"
fi

# Add deployment metadata
cat >> "$TEMP_SETTINGS" << EOF
# Deployment metadata (auto-generated by deploy-circuitpy.sh)
DEPLOYED_SCRIPT = "$SOURCE_FILE"
DEPLOYED_BASENAME = "$BASENAME.py"
DEPLOYED_DATE = "$(date "+%Y-%m-%d")"
DEPLOYED_TIMESTAMP = "$DATE_DEPLOYED"
DEPLOYED_SIZE = "$FILESIZE"
DEPLOYED_CHECKSUM = "$CHECKSUM"
EOF

# Copy to device
cp "$TEMP_SETTINGS" "$SETTINGS_FILE"
rm -f "$TEMP_SETTINGS"

echo "✅ Successfully deployed:"
echo "   • $SOURCE_FILE → code.py"
echo "   • $SOURCE_METADATA (updated)"
echo "   • $DEST_METADATA → device (size: ${FILESIZE} bytes)"
echo "   • settings.toml updated with deployment info"
echo "   • SHA256: ${CHECKSUM:0:16}..."
echo "🔄 The device should automatically restart with the new code"
echo ""
echo "💡 To identify what's running later:"
echo "   ls -l /Volumes/CIRCUITPY/code.py  # Look at filesize: $FILESIZE"
echo "   cat /Volumes/CIRCUITPY/${DEST_METADATA}  # Read full metadata"
echo "   cat /Volumes/CIRCUITPY/settings.toml  # Quick check"

echo "Done!"
